[global]
unity_version = "2022.3.35f1"
bundle_name = "KP_UnitedFront"
asset_directory = "Resources/Shader"
output_directory = "1.6/AssetBundles"
link_method = "junction"

[bundles.shaders]
bundle_path = "KP_UnitedFront"
bundle_name = "UFR_CutoutCarpace"
include_patterns = ["*.shader"]
targetless = false